import mysql.connector as mc
import pyttsx3
myCon = mc.connect( host="localhost", user= "root", passwd="Password123@", db = "bot_data")
mycursor = myCon.cursor()
engine = pyttsx3.init()
engine.say("Hello there, I am Bot. Your friendly neighbourhood Chatbot.")
engine.runAndWait()
print("Hello there, I am Bot. Your friendly neighbourhood Chatbot.")
engine.say("What's your name?")
engine.runAndWait()
user_name=input("What's your name? ")
engine.say("Nice to meet you," + str(user_name))
engine.runAndWait()
print("Nice to meet you,", user_name)
engine.say("What's your age? ")
engine.runAndWait()
age=int(input("What's your age? "))
engine.say("Where are you from? ")
engine.runAndWait()
home=input("Where are you from? ")
engine.say("Oh ," + str(home) + " is a nice place.")
engine.runAndWait()
print("Oh ," + home + " is a nice place.")
engine.say("What do you study? ")
engine.runAndWait()
course=input("What do you study? ")
sql = "INSERT INTO user_data (user_name, age, home, course) VALUES (%s, %s, %s, %s)"
val = (user_name, age, home, course)
mycursor.execute(sql, val)
myCon.commit()
print(mycursor.rowcount, "record inserted.")
mycursor.execute("SELECT * FROM USER_DATA")
rows = mycursor.fetchall()
print("Here is the User Data Table")
for row in rows:
    print(row)
mycursor.close()
myCon.close()    
print("Connection closed successfully.")                             