import mysql.connector as mc
import pyttsx3
engine = pyttsx3.init() 
engine.say("Hello there, I am Bot. Your friendly neighbourhood Chatbot.")
engine.runAndWait()
print("Hello there, I am Bot. Your friendly neighbourhood Chatbot.")
engine.say("What's your name?")
engine.runAndWait()
name=input("What's your name? ")
engine.say("Nice to meet you," + str(name))
engine.runAndWait()
print("Nice to meet you,", name)
engine.say("What's your age? ")
engine.runAndWait()
age=int(input("What's your age? "))
engine.say("Where are you from? ")
engine.runAndWait()
home=input("Where are you from? ")
engine.say("Oh ," + str(home) + " is a nice place.")
engine.runAndWait()
print("Oh ," + home + " is a nice place.")
engine.say("What do you study? ")
engine.runAndWait()
course=input("What do you study? ")
myCon = mc.connect( host="localhost", user= "root", passwd="root", db = "bot_data")
mycursor = myCon.cursor()
sql = "INSERT INTO user_data (name, age, home, course) VALUES (%s, %s, %s, %s)"
val = (name, age, home, course)
mycursor.execute(sql, val)
myCon.commit()
print(mycursor.rowcount, "record inserted.")
myCon.close()    
print("Connection closed successfully.")                             